### ISSUE TITLE
Question: GUID generation

### ISSUE THREAD

**Issue by bloyl** [NDAR/nda-tools#22]
I'm getting some pushback on installing/updating java and this tool was suggested as an alternative to the NDAR java web-services.

Unfortunately, I don't see a GUID creation tool. Did I miss it? are there any plans to provide one?

Thanks in advance.

**Comment by devjason** [comment]
Currently all GUID generation must be performed with the Java-based GUID Tool described at https://nda.nih.gov/s/guid/nda-guid.html due to how the current client and server technologies work together.

We are actually finishing up initial planning for new GUID infrastructure which will not require clients to use Java. Our current estimate is that it should be available by mid-2020.

**Comment by bloyl** [comment]
Thanks for the info.

**Comment by aaroneg** [comment]
@devjason did you all ever finish the thing to allow clients to not use java?
