### ISSUE TITLE
command should be pip3 install nda-tools 

### ISSUE THREAD

**Issue by RyanZurrin** [NDAR/nda-tools#62]
the command on the readme to install the nda-tools is pip install when it should be pip3 install. This will cause conflicts when trying to vtcmd and other commands.

**Comment by jacob-lee** [comment]
This isn't really a problem if the user knows which pip is being called on the path. Same thing, tbh, for calling `python` instead of `python3`).

If you know which python interpreter you are using, e.g. you've installed a python environment, then probably the safest thing to do is:

```
python -m pip install nda-tools
```

[as per documentation](https://pip.pypa.io/en/stable/)!
